version: 1
policy:
  # https://docs.taskcluster.net/docs/reference/integrations/taskcluster-github/docs/taskcluster-yml-v1#pull-requests
  pullRequests: collaborators
tasks:
  - $if: 'tasks_for == "github-push"'
    then:
      $if: 'event.ref == "refs/heads/auto" || event.ref == "refs/heads/try" || event.ref == "refs/heads/taskcluster"'
      then:
        taskGroupId: {$eval: as_slugid("decision_task")}
        taskId: {$eval: as_slugid("decision_task")}
        provisionerId: aws-provisioner-v1
        workerType: servo-docker-worker
        created: {$fromNow: ''}
        deadline: {$fromNow: '1 day'}
        metadata:
          name: "Servo: decision task"
          description: ""
          owner: ${event.pusher.name}@users.noreply.github.com
          source: ${event.compare}
        scopes:
          - "queue:scheduler-id:taskcluster-github"

          # Granted to role "repo:github.com/servo/servo:branch:*"
          - "queue:create-task:highest:aws-provisioner-v1/servo-*"
          - "queue:route:index.project.servo.servo.*"
          - "docker-worker:cache:cargo-registry-cache"
          - "docker-worker:cache:cargo-git-cache"

        payload:
          maxRunTime: {$eval: '20 * 60'}
          # https://github.com/servo/taskcluster-bootstrap-docker-images#decision-task
          image: "servobrowser/taskcluster-bootstrap:decision-task@sha256:28045b7ec0485ef363f8cb14f194008b47e9ede99f2ea40a1e945e921fce976e"
          features:
            taskclusterProxy: true
          env:
            GITHUB_EVENT_OWNER: ${event.pusher.name}@users.noreply.github.com
            GITHUB_EVENT_SOURCE: ${event.compare}
            GITHUB_EVENT_BRANCH: {$eval: 'event.ref[11:]'}
            GITHUB_EVENT_CLONE_URL: ${event.repository.clone_url}
            GITHUB_EVENT_COMMIT_SHA: ${event.after}
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone --depth 1 $GITHUB_EVENT_CLONE_URL --branch $GITHUB_EVENT_BRANCH repo &&
              cd repo &&
              git checkout $GITHUB_EVENT_COMMIT_SHA &&
              python3 etc/ci/taskcluster/decision-task.py
